# Theme: ozozFetch (by mmsaeed509) - customized for macOS
print_info() {
    info title
    info underline

    info "${c1} OS" os
    info "${c1} ├ " distro
    info "${c1} ├󰏗 " packages
    info "${c1} └ " shell
    echo
    info "${c2} DE/WM" wm
    info "${c2} ├ " term
    info "${c2} ├ " term_font
    info "${c2} └ " resolution
    echo
    info "${c3} PC" model
    info "${c3} ├󰍛 " cpu
    info "${c3} ├󰍹 " gpu
    info "${c3} ├ " memory

    info cols
}

# General
title_fqdn="off"
kernel_shorthand="on"
distro_shorthand="off"
os_arch="on"
uptime_shorthand="on"

# Memory
memory_percent="on"
memory_unit="gib"

# Packages
package_managers="on"

# Shell
shell_path="off"
shell_version="on"

# CPU
speed_type="bios_limit"
speed_shorthand="off"
cpu_brand="on"
cpu_speed="on"
cpu_cores="logical"
cpu_temp="off"

# GPU
gpu_brand="on"
gpu_type="all"

# Resolution
refresh_rate="on"

# Text
colors=(5 6 8 4 8 7)
bold="on"
underline_enabled="on"
underline_char="─"
separator="->"

# Color Blocks
block_range=(0 15)
color_blocks="on"
block_width=3
block_height=1
col_offset="auto"

# Image
image_backend="ascii"
image_source="auto"
ascii_distro="auto"
ascii_colors=(distro)
ascii_bold="on"
gap=2

# Misc
stdout="off"
